# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(677, 380)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(200, -1, 411, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Button_easy = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_easy.setObjectName("Button_easy")
        self.verticalLayout_3.addWidget(self.Button_easy)
        self.Button_medium = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_medium.setObjectName("Button_medium")
        self.verticalLayout_3.addWidget(self.Button_medium)
        self.Button_hard = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_hard.setObjectName("Button_hard")
        self.verticalLayout_3.addWidget(self.Button_hard)
        self.Guess_mo = QtWidgets.QCheckBox(self.centralwidget)
        self.Guess_mo.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.Guess_mo.setObjectName("Guess_mo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 677, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_easy.setText(_translate("MainWindow", "Лёгкий"))
        self.Button_medium.setText(_translate("MainWindow", "Средний"))
        self.Button_hard.setText(_translate("MainWindow", "Тяжёлый"))
        self.Guess_mo.setText(_translate("MainWindow", "Угадывание"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
